


::t*::TAM BAĞIMLI
::y*::YARI BAĞIMLI


::z*::ÖMERLİ
::x*::YEŞİLLİ



::s*::SONDA
::i*::İM TEDAVİ
::v*::İV TEDAVİ
::g*::GTM
::c*:: SUBKUTAN ENJEKSİYON
::n*::NAKİL
::H*::TAHLİL
::p*::PANSUMAN
::ş*::ŞEHRİBAN ABA

;;TANI
::yş*::YAŞLILIK
::Yd*::YUMUŞAK DOKU BOZUKLUĞU



::eb*::EVDE BAKIM HASTASI, TARAFIMIZCA EVDE GÖRÜLDÜ HARAKET KISITLIĞI MEVCUT  TEDAVİSİ, İLAÇLARI İÇİN YETKİLİ BRANŞ UZMANI İHTİYACI TARAFINIZCA DEĞERLENDİRİLMESİ RİCA OLUNUR.
